// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbqueries

import (
	"database/sql"
)

type Url struct {
	ID        int32
	Alias     string
	Url       string
	Count     int32
	CreatedAt sql.NullTime
}
