CREATE TABLE urls (
    id SERIAL PRIMARY KEY,
    alias varchar(255) NOT NULL UNIQUE,
    url TEXT NOT NULL,
    count integer NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);